version: 2.1

orbs:
  node: circleci/node@4.7

executors:
  default-executor:
    docker:
      - image: circleci/node:14

jobs:
  cicd-job:
    executor:
      name: default-executor
    steps:
      - checkout
      - run:
          name: Install dependencies - NPM packages
          command: npm install
      - run:
          name: Run tests
          command: npm run test:babel
      - run:
          name: Run linter
          command: npm run lint

workflows:
  version: 2
  example-workflow:
    jobs:
      - cicd-job
