version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  cicd-job:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          name: install dependencies -NPM packeges
          command: npm install
      - run:
          name: run tests
          command: PORT=8080 npm run test
      - run:
          name: Run linter
          command: npm run lint
      - run:
          name: CD - Deploy the service
          command: curl "https://api.render.com/deploy/srv-cgklotorddleudv9dsb0?key=6VS8jqX9XDQ"

workflows:
  example-workflow:
    jobs:
      - cicd-job
